image: python:3.8.5-slim

before_script:
    - apt -y update && apt -y install git
    - python -m pip install pdoc3 requests

build_docs:
    script:
        - python -m pip install -r requirements.txt
        - pdoc --html haveibeenpywned -o docs --force
        - git config --global user.email "$CI_COMMIT_EMAIL"
        - git config --global user.name "$CI_COMMIT_NAME"
        - git add docs
        - git commit -m "Auto build docs for $CI_COMMIT_SHORT_SHA" || echo "No changes, nothing to commit!"
        - git remote remove origin && git remote add origin https://$CI_TOKEN_USER:$CI_TOKEN_PASS@gitlab.com/$CI_PROJECT_PATH.git
        - git push origin HEAD:$CI_COMMIT_REF_NAME # Pushes to the same branch as the trigger
