name: Re-generate Documentation
on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8.5]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3 requests
          pip install -r requirements.txt
      - name: Build docs
        run: pdoc --html haveibeenpywned -o docs --force

      - name: Commit & push
        uses: EndBug/add-and-commit@v4.4.0
        with:
          author_name: Sam
          author_email: sam.w.neal@gmail.com
          message: "Auto build docs for ${{ github.sha }}"
          add: "docs/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
